name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Run workflow on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Allow workflow to write to repository

    steps:
      # Step 1: Checkout code from branch main
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # Step 3: Install dependencies using npm
      - name: Install dependencies
        run: npm install

      # Step 4: Build project
      - name: Build project
        run: npm run build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
